'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace NGLLaneObjectWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="LaneObjectSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(clsImportDataBase))>  _
    Partial Public Class LaneObject
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private LastErrorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessDataExOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessDataWCalendarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessData60OperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessData60WCalendarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessData70OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.DTMSTestWebServices.My.MySettings.Default.DTMSTestWebServices_NGLLaneObjectWS_LaneObject
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event LastErrorCompleted As LastErrorCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessDataCompleted As ProcessDataCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessDataExCompleted As ProcessDataExCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessDataWCalendarCompleted As ProcessDataWCalendarCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessData60Completed As ProcessData60CompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessData60WCalendarCompleted As ProcessData60WCalendarCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessData70Completed As ProcessData70CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LastError", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LastError() As String
            Dim results() As Object = Me.Invoke("LastError", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LastErrorAsync()
            Me.LastErrorAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LastErrorAsync(ByVal userState As Object)
            If (Me.LastErrorOperationCompleted Is Nothing) Then
                Me.LastErrorOperationCompleted = AddressOf Me.OnLastErrorOperationCompleted
            End If
            Me.InvokeAsync("LastError", New Object(-1) {}, Me.LastErrorOperationCompleted, userState)
        End Sub
        
        Private Sub OnLastErrorOperationCompleted(ByVal arg As Object)
            If (Not (Me.LastErrorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LastErrorCompleted(Me, New LastErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessData(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject) As Integer
            Dim results() As Object = Me.Invoke("ProcessData", New Object() {AuthorizationCode, Lanes})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessDataAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject)
            Me.ProcessDataAsync(AuthorizationCode, Lanes, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessDataAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject, ByVal userState As Object)
            If (Me.ProcessDataOperationCompleted Is Nothing) Then
                Me.ProcessDataOperationCompleted = AddressOf Me.OnProcessDataOperationCompleted
            End If
            Me.InvokeAsync("ProcessData", New Object() {AuthorizationCode, Lanes}, Me.ProcessDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessDataCompleted(Me, New ProcessDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessDataEx", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessDataEx(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject, ByRef ReturnMessage As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessDataEx", New Object() {AuthorizationCode, Lanes, ReturnMessage})
            ReturnMessage = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessDataExAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject, ByVal ReturnMessage As String)
            Me.ProcessDataExAsync(AuthorizationCode, Lanes, ReturnMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessDataExAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject, ByVal ReturnMessage As String, ByVal userState As Object)
            If (Me.ProcessDataExOperationCompleted Is Nothing) Then
                Me.ProcessDataExOperationCompleted = AddressOf Me.OnProcessDataExOperationCompleted
            End If
            Me.InvokeAsync("ProcessDataEx", New Object() {AuthorizationCode, Lanes, ReturnMessage}, Me.ProcessDataExOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessDataExOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessDataExCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessDataExCompleted(Me, New ProcessDataExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessDataWCalendar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessDataWCalendar(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject, ByVal Calendar() As clsLaneCalendarObject, ByRef ReturnMessage As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessDataWCalendar", New Object() {AuthorizationCode, Lanes, Calendar, ReturnMessage})
            ReturnMessage = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessDataWCalendarAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject, ByVal Calendar() As clsLaneCalendarObject, ByVal ReturnMessage As String)
            Me.ProcessDataWCalendarAsync(AuthorizationCode, Lanes, Calendar, ReturnMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessDataWCalendarAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject, ByVal Calendar() As clsLaneCalendarObject, ByVal ReturnMessage As String, ByVal userState As Object)
            If (Me.ProcessDataWCalendarOperationCompleted Is Nothing) Then
                Me.ProcessDataWCalendarOperationCompleted = AddressOf Me.OnProcessDataWCalendarOperationCompleted
            End If
            Me.InvokeAsync("ProcessDataWCalendar", New Object() {AuthorizationCode, Lanes, Calendar, ReturnMessage}, Me.ProcessDataWCalendarOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessDataWCalendarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessDataWCalendarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessDataWCalendarCompleted(Me, New ProcessDataWCalendarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData60", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessData60(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject60, ByRef ReturnMessage As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessData60", New Object() {AuthorizationCode, Lanes, ReturnMessage})
            ReturnMessage = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessData60Async(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject60, ByVal ReturnMessage As String)
            Me.ProcessData60Async(AuthorizationCode, Lanes, ReturnMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessData60Async(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject60, ByVal ReturnMessage As String, ByVal userState As Object)
            If (Me.ProcessData60OperationCompleted Is Nothing) Then
                Me.ProcessData60OperationCompleted = AddressOf Me.OnProcessData60OperationCompleted
            End If
            Me.InvokeAsync("ProcessData60", New Object() {AuthorizationCode, Lanes, ReturnMessage}, Me.ProcessData60OperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessData60OperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessData60CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessData60Completed(Me, New ProcessData60CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData60WCalendar", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessData60WCalendar(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject60, ByVal Calendar() As clsLaneCalendarObject60, ByRef ReturnMessage As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessData60WCalendar", New Object() {AuthorizationCode, Lanes, Calendar, ReturnMessage})
            ReturnMessage = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessData60WCalendarAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject60, ByVal Calendar() As clsLaneCalendarObject60, ByVal ReturnMessage As String)
            Me.ProcessData60WCalendarAsync(AuthorizationCode, Lanes, Calendar, ReturnMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessData60WCalendarAsync(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject60, ByVal Calendar() As clsLaneCalendarObject60, ByVal ReturnMessage As String, ByVal userState As Object)
            If (Me.ProcessData60WCalendarOperationCompleted Is Nothing) Then
                Me.ProcessData60WCalendarOperationCompleted = AddressOf Me.OnProcessData60WCalendarOperationCompleted
            End If
            Me.InvokeAsync("ProcessData60WCalendar", New Object() {AuthorizationCode, Lanes, Calendar, ReturnMessage}, Me.ProcessData60WCalendarOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessData60WCalendarOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessData60WCalendarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessData60WCalendarCompleted(Me, New ProcessData60WCalendarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData70", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessData70(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject70, ByVal Calendar() As clsLaneCalendarObject70, ByRef ReturnMessage As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessData70", New Object() {AuthorizationCode, Lanes, Calendar, ReturnMessage})
            ReturnMessage = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessData70Async(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject70, ByVal Calendar() As clsLaneCalendarObject70, ByVal ReturnMessage As String)
            Me.ProcessData70Async(AuthorizationCode, Lanes, Calendar, ReturnMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessData70Async(ByVal AuthorizationCode As String, ByVal Lanes() As clsLaneObject70, ByVal Calendar() As clsLaneCalendarObject70, ByVal ReturnMessage As String, ByVal userState As Object)
            If (Me.ProcessData70OperationCompleted Is Nothing) Then
                Me.ProcessData70OperationCompleted = AddressOf Me.OnProcessData70OperationCompleted
            End If
            Me.InvokeAsync("ProcessData70", New Object() {AuthorizationCode, Lanes, Calendar, ReturnMessage}, Me.ProcessData70OperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessData70OperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessData70CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessData70Completed(Me, New ProcessData70CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsLaneObject
        
        Private laneNumberField As String
        
        Private laneNameField As String
        
        Private laneNumberMasterField As String
        
        Private laneNameMasterField As String
        
        Private laneCompNumberField As String
        
        Private laneDefaultCarrierUseField As Boolean
        
        Private laneDefaultCarrierNumberField As Integer
        
        Private laneOrigCompNumberField As String
        
        Private laneOrigNameField As String
        
        Private laneOrigAddress1Field As String
        
        Private laneOrigAddress2Field As String
        
        Private laneOrigAddress3Field As String
        
        Private laneOrigCityField As String
        
        Private laneOrigStateField As String
        
        Private laneOrigCountryField As String
        
        Private laneOrigZipField As String
        
        Private laneOrigContactPhoneField As String
        
        Private laneOrigContactPhoneExtField As String
        
        Private laneOrigContactFaxField As String
        
        Private laneDestCompNumberField As String
        
        Private laneDestNameField As String
        
        Private laneDestAddress1Field As String
        
        Private laneDestAddress2Field As String
        
        Private laneDestAddress3Field As String
        
        Private laneDestCityField As String
        
        Private laneDestStateField As String
        
        Private laneDestCountryField As String
        
        Private laneDestZipField As String
        
        Private laneDestContactPhoneField As String
        
        Private laneDestContactPhoneExtField As String
        
        Private laneDestContactFaxField As String
        
        Private laneConsigneeNumberField As String
        
        Private laneRecMinInField As Integer
        
        Private laneRecMinUnloadField As Integer
        
        Private laneRecMinOutField As Integer
        
        Private laneApptField As Boolean
        
        Private lanePalletExchangeField As Boolean
        
        Private lanePalletTypeField As String
        
        Private laneBenchMilesField As Integer
        
        Private laneBFCField As Double
        
        Private laneBFCTypeField As String
        
        Private laneRecHourStartField As String
        
        Private laneRecHourStopField As String
        
        Private laneDestHourStartField As String
        
        Private laneDestHourStopField As String
        
        Private laneCommentsField As String
        
        Private laneCommentsConfidentialField As String
        
        Private laneLatitudeField As Double
        
        Private laneLongitudeField As Double
        
        Private laneTempTypeField As Short
        
        Private laneTransTypeField As Short
        
        Private lanePrimaryBuyerField As String
        
        Private laneAptDeliveryField As Boolean
        
        Private brokerNumberField As String
        
        Private brokerNameField As String
        
        Private laneOriginAddressUseField As Boolean
        
        Private laneCarrierEquipmentCodesField As String
        
        Private laneChepGLIDField As String
        
        Private laneCarrierTypeCodeField As String
        
        Private lanePickUpMonField As Boolean
        
        Private lanePickUpTueField As Boolean
        
        Private lanePickUpWedField As Boolean
        
        Private lanePickUpThuField As Boolean
        
        Private lanePickUpFriField As Boolean
        
        Private lanePickUpSatField As Boolean
        
        Private lanePickUpSunField As Boolean
        
        Private laneDropOffMonField As Boolean
        
        Private laneDropOffTueField As Boolean
        
        Private laneDropOffWedField As Boolean
        
        Private laneDropOffThuField As Boolean
        
        Private laneDropOffFriField As Boolean
        
        Private laneDropOffSatField As Boolean
        
        Private laneDropOffSunField As Boolean
        
        '''<remarks/>
        Public Property LaneNumber() As String
            Get
                Return Me.laneNumberField
            End Get
            Set
                Me.laneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneName() As String
            Get
                Return Me.laneNameField
            End Get
            Set
                Me.laneNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneNumberMaster() As String
            Get
                Return Me.laneNumberMasterField
            End Get
            Set
                Me.laneNumberMasterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneNameMaster() As String
            Get
                Return Me.laneNameMasterField
            End Get
            Set
                Me.laneNameMasterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCompNumber() As String
            Get
                Return Me.laneCompNumberField
            End Get
            Set
                Me.laneCompNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDefaultCarrierUse() As Boolean
            Get
                Return Me.laneDefaultCarrierUseField
            End Get
            Set
                Me.laneDefaultCarrierUseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDefaultCarrierNumber() As Integer
            Get
                Return Me.laneDefaultCarrierNumberField
            End Get
            Set
                Me.laneDefaultCarrierNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigCompNumber() As String
            Get
                Return Me.laneOrigCompNumberField
            End Get
            Set
                Me.laneOrigCompNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigName() As String
            Get
                Return Me.laneOrigNameField
            End Get
            Set
                Me.laneOrigNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigAddress1() As String
            Get
                Return Me.laneOrigAddress1Field
            End Get
            Set
                Me.laneOrigAddress1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigAddress2() As String
            Get
                Return Me.laneOrigAddress2Field
            End Get
            Set
                Me.laneOrigAddress2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigAddress3() As String
            Get
                Return Me.laneOrigAddress3Field
            End Get
            Set
                Me.laneOrigAddress3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigCity() As String
            Get
                Return Me.laneOrigCityField
            End Get
            Set
                Me.laneOrigCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigState() As String
            Get
                Return Me.laneOrigStateField
            End Get
            Set
                Me.laneOrigStateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigCountry() As String
            Get
                Return Me.laneOrigCountryField
            End Get
            Set
                Me.laneOrigCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigZip() As String
            Get
                Return Me.laneOrigZipField
            End Get
            Set
                Me.laneOrigZipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigContactPhone() As String
            Get
                Return Me.laneOrigContactPhoneField
            End Get
            Set
                Me.laneOrigContactPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigContactPhoneExt() As String
            Get
                Return Me.laneOrigContactPhoneExtField
            End Get
            Set
                Me.laneOrigContactPhoneExtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigContactFax() As String
            Get
                Return Me.laneOrigContactFaxField
            End Get
            Set
                Me.laneOrigContactFaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestCompNumber() As String
            Get
                Return Me.laneDestCompNumberField
            End Get
            Set
                Me.laneDestCompNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestName() As String
            Get
                Return Me.laneDestNameField
            End Get
            Set
                Me.laneDestNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestAddress1() As String
            Get
                Return Me.laneDestAddress1Field
            End Get
            Set
                Me.laneDestAddress1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestAddress2() As String
            Get
                Return Me.laneDestAddress2Field
            End Get
            Set
                Me.laneDestAddress2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestAddress3() As String
            Get
                Return Me.laneDestAddress3Field
            End Get
            Set
                Me.laneDestAddress3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestCity() As String
            Get
                Return Me.laneDestCityField
            End Get
            Set
                Me.laneDestCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestState() As String
            Get
                Return Me.laneDestStateField
            End Get
            Set
                Me.laneDestStateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestCountry() As String
            Get
                Return Me.laneDestCountryField
            End Get
            Set
                Me.laneDestCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestZip() As String
            Get
                Return Me.laneDestZipField
            End Get
            Set
                Me.laneDestZipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestContactPhone() As String
            Get
                Return Me.laneDestContactPhoneField
            End Get
            Set
                Me.laneDestContactPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestContactPhoneExt() As String
            Get
                Return Me.laneDestContactPhoneExtField
            End Get
            Set
                Me.laneDestContactPhoneExtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestContactFax() As String
            Get
                Return Me.laneDestContactFaxField
            End Get
            Set
                Me.laneDestContactFaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneConsigneeNumber() As String
            Get
                Return Me.laneConsigneeNumberField
            End Get
            Set
                Me.laneConsigneeNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecMinIn() As Integer
            Get
                Return Me.laneRecMinInField
            End Get
            Set
                Me.laneRecMinInField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecMinUnload() As Integer
            Get
                Return Me.laneRecMinUnloadField
            End Get
            Set
                Me.laneRecMinUnloadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecMinOut() As Integer
            Get
                Return Me.laneRecMinOutField
            End Get
            Set
                Me.laneRecMinOutField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneAppt() As Boolean
            Get
                Return Me.laneApptField
            End Get
            Set
                Me.laneApptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePalletExchange() As Boolean
            Get
                Return Me.lanePalletExchangeField
            End Get
            Set
                Me.lanePalletExchangeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePalletType() As String
            Get
                Return Me.lanePalletTypeField
            End Get
            Set
                Me.lanePalletTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneBenchMiles() As Integer
            Get
                Return Me.laneBenchMilesField
            End Get
            Set
                Me.laneBenchMilesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneBFC() As Double
            Get
                Return Me.laneBFCField
            End Get
            Set
                Me.laneBFCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneBFCType() As String
            Get
                Return Me.laneBFCTypeField
            End Get
            Set
                Me.laneBFCTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecHourStart() As String
            Get
                Return Me.laneRecHourStartField
            End Get
            Set
                Me.laneRecHourStartField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecHourStop() As String
            Get
                Return Me.laneRecHourStopField
            End Get
            Set
                Me.laneRecHourStopField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestHourStart() As String
            Get
                Return Me.laneDestHourStartField
            End Get
            Set
                Me.laneDestHourStartField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestHourStop() As String
            Get
                Return Me.laneDestHourStopField
            End Get
            Set
                Me.laneDestHourStopField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneComments() As String
            Get
                Return Me.laneCommentsField
            End Get
            Set
                Me.laneCommentsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCommentsConfidential() As String
            Get
                Return Me.laneCommentsConfidentialField
            End Get
            Set
                Me.laneCommentsConfidentialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneLatitude() As Double
            Get
                Return Me.laneLatitudeField
            End Get
            Set
                Me.laneLatitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneLongitude() As Double
            Get
                Return Me.laneLongitudeField
            End Get
            Set
                Me.laneLongitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneTempType() As Short
            Get
                Return Me.laneTempTypeField
            End Get
            Set
                Me.laneTempTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneTransType() As Short
            Get
                Return Me.laneTransTypeField
            End Get
            Set
                Me.laneTransTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePrimaryBuyer() As String
            Get
                Return Me.lanePrimaryBuyerField
            End Get
            Set
                Me.lanePrimaryBuyerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneAptDelivery() As Boolean
            Get
                Return Me.laneAptDeliveryField
            End Get
            Set
                Me.laneAptDeliveryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BrokerNumber() As String
            Get
                Return Me.brokerNumberField
            End Get
            Set
                Me.brokerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BrokerName() As String
            Get
                Return Me.brokerNameField
            End Get
            Set
                Me.brokerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOriginAddressUse() As Boolean
            Get
                Return Me.laneOriginAddressUseField
            End Get
            Set
                Me.laneOriginAddressUseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCarrierEquipmentCodes() As String
            Get
                Return Me.laneCarrierEquipmentCodesField
            End Get
            Set
                Me.laneCarrierEquipmentCodesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneChepGLID() As String
            Get
                Return Me.laneChepGLIDField
            End Get
            Set
                Me.laneChepGLIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCarrierTypeCode() As String
            Get
                Return Me.laneCarrierTypeCodeField
            End Get
            Set
                Me.laneCarrierTypeCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpMon() As Boolean
            Get
                Return Me.lanePickUpMonField
            End Get
            Set
                Me.lanePickUpMonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpTue() As Boolean
            Get
                Return Me.lanePickUpTueField
            End Get
            Set
                Me.lanePickUpTueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpWed() As Boolean
            Get
                Return Me.lanePickUpWedField
            End Get
            Set
                Me.lanePickUpWedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpThu() As Boolean
            Get
                Return Me.lanePickUpThuField
            End Get
            Set
                Me.lanePickUpThuField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpFri() As Boolean
            Get
                Return Me.lanePickUpFriField
            End Get
            Set
                Me.lanePickUpFriField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpSat() As Boolean
            Get
                Return Me.lanePickUpSatField
            End Get
            Set
                Me.lanePickUpSatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpSun() As Boolean
            Get
                Return Me.lanePickUpSunField
            End Get
            Set
                Me.lanePickUpSunField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffMon() As Boolean
            Get
                Return Me.laneDropOffMonField
            End Get
            Set
                Me.laneDropOffMonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffTue() As Boolean
            Get
                Return Me.laneDropOffTueField
            End Get
            Set
                Me.laneDropOffTueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffWed() As Boolean
            Get
                Return Me.laneDropOffWedField
            End Get
            Set
                Me.laneDropOffWedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffThu() As Boolean
            Get
                Return Me.laneDropOffThuField
            End Get
            Set
                Me.laneDropOffThuField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffFri() As Boolean
            Get
                Return Me.laneDropOffFriField
            End Get
            Set
                Me.laneDropOffFriField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffSat() As Boolean
            Get
                Return Me.laneDropOffSatField
            End Get
            Set
                Me.laneDropOffSatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffSun() As Boolean
            Get
                Return Me.laneDropOffSunField
            End Get
            Set
                Me.laneDropOffSunField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(clsLaneCalendarObject60)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(clsLaneCalendarObject70)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(clsLaneObject60)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(clsLaneObject70)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsImportDataBase
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(clsLaneCalendarObject70)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsLaneCalendarObject60
        Inherits clsImportDataBase
        
        Private laneNumberField As String
        
        Private monthField As Integer
        
        Private dayField As Integer
        
        Private openField As Boolean
        
        Private startTimeField As String
        
        Private endTimeField As String
        
        Private isHolidayField As Boolean
        
        Private applyToOriginField As Boolean
        
        '''<remarks/>
        Public Property LaneNumber() As String
            Get
                Return Me.laneNumberField
            End Get
            Set
                Me.laneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Month() As Integer
            Get
                Return Me.monthField
            End Get
            Set
                Me.monthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Day() As Integer
            Get
                Return Me.dayField
            End Get
            Set
                Me.dayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Open() As Boolean
            Get
                Return Me.openField
            End Get
            Set
                Me.openField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartTime() As String
            Get
                Return Me.startTimeField
            End Get
            Set
                Me.startTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndTime() As String
            Get
                Return Me.endTimeField
            End Get
            Set
                Me.endTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsHoliday() As Boolean
            Get
                Return Me.isHolidayField
            End Get
            Set
                Me.isHolidayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplyToOrigin() As Boolean
            Get
                Return Me.applyToOriginField
            End Get
            Set
                Me.applyToOriginField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsLaneCalendarObject70
        Inherits clsLaneCalendarObject60
        
        Private laneLegalEntityField As String
        
        Private laneCompAlphaCodeField As String
        
        '''<remarks/>
        Public Property LaneLegalEntity() As String
            Get
                Return Me.laneLegalEntityField
            End Get
            Set
                Me.laneLegalEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCompAlphaCode() As String
            Get
                Return Me.laneCompAlphaCodeField
            End Get
            Set
                Me.laneCompAlphaCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(clsLaneObject70)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsLaneObject60
        Inherits clsImportDataBase
        
        Private _BrokerNumberField As String
        
        Private _BrokerNameField As String
        
        Private laneNumberField As String
        
        Private laneNameField As String
        
        Private laneNumberMasterField As String
        
        Private laneNameMasterField As String
        
        Private laneCompNumberField As String
        
        Private laneDefaultCarrierUseField As Boolean
        
        Private laneDefaultCarrierNumberField As Integer
        
        Private laneOrigCompNumberField As String
        
        Private laneOrigNameField As String
        
        Private laneOrigAddress1Field As String
        
        Private laneOrigAddress2Field As String
        
        Private laneOrigAddress3Field As String
        
        Private laneOrigCityField As String
        
        Private laneOrigStateField As String
        
        Private laneOrigCountryField As String
        
        Private laneOrigZipField As String
        
        Private laneOrigContactPhoneField As String
        
        Private laneOrigContactPhoneExtField As String
        
        Private laneOrigContactFaxField As String
        
        Private laneDestCompNumberField As String
        
        Private laneDestNameField As String
        
        Private laneDestAddress1Field As String
        
        Private laneDestAddress2Field As String
        
        Private laneDestAddress3Field As String
        
        Private laneDestCityField As String
        
        Private laneDestStateField As String
        
        Private laneDestCountryField As String
        
        Private laneDestZipField As String
        
        Private laneDestContactPhoneField As String
        
        Private laneDestContactPhoneExtField As String
        
        Private laneDestContactFaxField As String
        
        Private laneConsigneeNumberField As String
        
        Private laneRecMinInField As Integer
        
        Private laneRecMinUnloadField As Integer
        
        Private laneRecMinOutField As Integer
        
        Private laneApptField As Boolean
        
        Private lanePalletExchangeField As Boolean
        
        Private lanePalletTypeField As String
        
        Private laneBenchMilesField As Integer
        
        Private laneBFCField As Double
        
        Private laneBFCTypeField As String
        
        Private laneRecHourStartField As String
        
        Private laneRecHourStopField As String
        
        Private laneDestHourStartField As String
        
        Private laneDestHourStopField As String
        
        Private laneCommentsField As String
        
        Private laneCommentsConfidentialField As String
        
        Private laneLatitudeField As Double
        
        Private laneLongitudeField As Double
        
        Private laneTempTypeField As Short
        
        Private laneTransTypeField As Short
        
        Private lanePrimaryBuyerField As String
        
        Private laneAptDeliveryField As Boolean
        
        Private brokerNumberField As String
        
        Private brokerNameField As String
        
        Private laneOriginAddressUseField As Boolean
        
        Private laneCarrierEquipmentCodesField As String
        
        Private laneChepGLIDField As String
        
        Private laneCarrierTypeCodeField As String
        
        Private lanePickUpMonField As Boolean
        
        Private lanePickUpTueField As Boolean
        
        Private lanePickUpWedField As Boolean
        
        Private lanePickUpThuField As Boolean
        
        Private lanePickUpFriField As Boolean
        
        Private lanePickUpSatField As Boolean
        
        Private lanePickUpSunField As Boolean
        
        Private laneDropOffMonField As Boolean
        
        Private laneDropOffTueField As Boolean
        
        Private laneDropOffWedField As Boolean
        
        Private laneDropOffThuField As Boolean
        
        Private laneDropOffFriField As Boolean
        
        Private laneDropOffSatField As Boolean
        
        Private laneDropOffSunField As Boolean
        
        Private laneDefaultRouteSequenceField As Integer
        
        Private laneRouteGuideNumberField As String
        
        Private laneIsCrossDockFacilityField As Boolean
        
        '''<remarks/>
        Public Property _BrokerNumber() As String
            Get
                Return Me._BrokerNumberField
            End Get
            Set
                Me._BrokerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property _BrokerName() As String
            Get
                Return Me._BrokerNameField
            End Get
            Set
                Me._BrokerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneNumber() As String
            Get
                Return Me.laneNumberField
            End Get
            Set
                Me.laneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneName() As String
            Get
                Return Me.laneNameField
            End Get
            Set
                Me.laneNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneNumberMaster() As String
            Get
                Return Me.laneNumberMasterField
            End Get
            Set
                Me.laneNumberMasterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneNameMaster() As String
            Get
                Return Me.laneNameMasterField
            End Get
            Set
                Me.laneNameMasterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCompNumber() As String
            Get
                Return Me.laneCompNumberField
            End Get
            Set
                Me.laneCompNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDefaultCarrierUse() As Boolean
            Get
                Return Me.laneDefaultCarrierUseField
            End Get
            Set
                Me.laneDefaultCarrierUseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDefaultCarrierNumber() As Integer
            Get
                Return Me.laneDefaultCarrierNumberField
            End Get
            Set
                Me.laneDefaultCarrierNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigCompNumber() As String
            Get
                Return Me.laneOrigCompNumberField
            End Get
            Set
                Me.laneOrigCompNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigName() As String
            Get
                Return Me.laneOrigNameField
            End Get
            Set
                Me.laneOrigNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigAddress1() As String
            Get
                Return Me.laneOrigAddress1Field
            End Get
            Set
                Me.laneOrigAddress1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigAddress2() As String
            Get
                Return Me.laneOrigAddress2Field
            End Get
            Set
                Me.laneOrigAddress2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigAddress3() As String
            Get
                Return Me.laneOrigAddress3Field
            End Get
            Set
                Me.laneOrigAddress3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigCity() As String
            Get
                Return Me.laneOrigCityField
            End Get
            Set
                Me.laneOrigCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigState() As String
            Get
                Return Me.laneOrigStateField
            End Get
            Set
                Me.laneOrigStateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigCountry() As String
            Get
                Return Me.laneOrigCountryField
            End Get
            Set
                Me.laneOrigCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigZip() As String
            Get
                Return Me.laneOrigZipField
            End Get
            Set
                Me.laneOrigZipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigContactPhone() As String
            Get
                Return Me.laneOrigContactPhoneField
            End Get
            Set
                Me.laneOrigContactPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigContactPhoneExt() As String
            Get
                Return Me.laneOrigContactPhoneExtField
            End Get
            Set
                Me.laneOrigContactPhoneExtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigContactFax() As String
            Get
                Return Me.laneOrigContactFaxField
            End Get
            Set
                Me.laneOrigContactFaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestCompNumber() As String
            Get
                Return Me.laneDestCompNumberField
            End Get
            Set
                Me.laneDestCompNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestName() As String
            Get
                Return Me.laneDestNameField
            End Get
            Set
                Me.laneDestNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestAddress1() As String
            Get
                Return Me.laneDestAddress1Field
            End Get
            Set
                Me.laneDestAddress1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestAddress2() As String
            Get
                Return Me.laneDestAddress2Field
            End Get
            Set
                Me.laneDestAddress2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestAddress3() As String
            Get
                Return Me.laneDestAddress3Field
            End Get
            Set
                Me.laneDestAddress3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestCity() As String
            Get
                Return Me.laneDestCityField
            End Get
            Set
                Me.laneDestCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestState() As String
            Get
                Return Me.laneDestStateField
            End Get
            Set
                Me.laneDestStateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestCountry() As String
            Get
                Return Me.laneDestCountryField
            End Get
            Set
                Me.laneDestCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestZip() As String
            Get
                Return Me.laneDestZipField
            End Get
            Set
                Me.laneDestZipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestContactPhone() As String
            Get
                Return Me.laneDestContactPhoneField
            End Get
            Set
                Me.laneDestContactPhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestContactPhoneExt() As String
            Get
                Return Me.laneDestContactPhoneExtField
            End Get
            Set
                Me.laneDestContactPhoneExtField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestContactFax() As String
            Get
                Return Me.laneDestContactFaxField
            End Get
            Set
                Me.laneDestContactFaxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneConsigneeNumber() As String
            Get
                Return Me.laneConsigneeNumberField
            End Get
            Set
                Me.laneConsigneeNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecMinIn() As Integer
            Get
                Return Me.laneRecMinInField
            End Get
            Set
                Me.laneRecMinInField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecMinUnload() As Integer
            Get
                Return Me.laneRecMinUnloadField
            End Get
            Set
                Me.laneRecMinUnloadField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecMinOut() As Integer
            Get
                Return Me.laneRecMinOutField
            End Get
            Set
                Me.laneRecMinOutField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneAppt() As Boolean
            Get
                Return Me.laneApptField
            End Get
            Set
                Me.laneApptField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePalletExchange() As Boolean
            Get
                Return Me.lanePalletExchangeField
            End Get
            Set
                Me.lanePalletExchangeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePalletType() As String
            Get
                Return Me.lanePalletTypeField
            End Get
            Set
                Me.lanePalletTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneBenchMiles() As Integer
            Get
                Return Me.laneBenchMilesField
            End Get
            Set
                Me.laneBenchMilesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneBFC() As Double
            Get
                Return Me.laneBFCField
            End Get
            Set
                Me.laneBFCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneBFCType() As String
            Get
                Return Me.laneBFCTypeField
            End Get
            Set
                Me.laneBFCTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecHourStart() As String
            Get
                Return Me.laneRecHourStartField
            End Get
            Set
                Me.laneRecHourStartField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRecHourStop() As String
            Get
                Return Me.laneRecHourStopField
            End Get
            Set
                Me.laneRecHourStopField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestHourStart() As String
            Get
                Return Me.laneDestHourStartField
            End Get
            Set
                Me.laneDestHourStartField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestHourStop() As String
            Get
                Return Me.laneDestHourStopField
            End Get
            Set
                Me.laneDestHourStopField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneComments() As String
            Get
                Return Me.laneCommentsField
            End Get
            Set
                Me.laneCommentsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCommentsConfidential() As String
            Get
                Return Me.laneCommentsConfidentialField
            End Get
            Set
                Me.laneCommentsConfidentialField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneLatitude() As Double
            Get
                Return Me.laneLatitudeField
            End Get
            Set
                Me.laneLatitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneLongitude() As Double
            Get
                Return Me.laneLongitudeField
            End Get
            Set
                Me.laneLongitudeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneTempType() As Short
            Get
                Return Me.laneTempTypeField
            End Get
            Set
                Me.laneTempTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneTransType() As Short
            Get
                Return Me.laneTransTypeField
            End Get
            Set
                Me.laneTransTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePrimaryBuyer() As String
            Get
                Return Me.lanePrimaryBuyerField
            End Get
            Set
                Me.lanePrimaryBuyerField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneAptDelivery() As Boolean
            Get
                Return Me.laneAptDeliveryField
            End Get
            Set
                Me.laneAptDeliveryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BrokerNumber() As String
            Get
                Return Me.brokerNumberField
            End Get
            Set
                Me.brokerNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BrokerName() As String
            Get
                Return Me.brokerNameField
            End Get
            Set
                Me.brokerNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOriginAddressUse() As Boolean
            Get
                Return Me.laneOriginAddressUseField
            End Get
            Set
                Me.laneOriginAddressUseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCarrierEquipmentCodes() As String
            Get
                Return Me.laneCarrierEquipmentCodesField
            End Get
            Set
                Me.laneCarrierEquipmentCodesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneChepGLID() As String
            Get
                Return Me.laneChepGLIDField
            End Get
            Set
                Me.laneChepGLIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCarrierTypeCode() As String
            Get
                Return Me.laneCarrierTypeCodeField
            End Get
            Set
                Me.laneCarrierTypeCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpMon() As Boolean
            Get
                Return Me.lanePickUpMonField
            End Get
            Set
                Me.lanePickUpMonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpTue() As Boolean
            Get
                Return Me.lanePickUpTueField
            End Get
            Set
                Me.lanePickUpTueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpWed() As Boolean
            Get
                Return Me.lanePickUpWedField
            End Get
            Set
                Me.lanePickUpWedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpThu() As Boolean
            Get
                Return Me.lanePickUpThuField
            End Get
            Set
                Me.lanePickUpThuField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpFri() As Boolean
            Get
                Return Me.lanePickUpFriField
            End Get
            Set
                Me.lanePickUpFriField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpSat() As Boolean
            Get
                Return Me.lanePickUpSatField
            End Get
            Set
                Me.lanePickUpSatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LanePickUpSun() As Boolean
            Get
                Return Me.lanePickUpSunField
            End Get
            Set
                Me.lanePickUpSunField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffMon() As Boolean
            Get
                Return Me.laneDropOffMonField
            End Get
            Set
                Me.laneDropOffMonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffTue() As Boolean
            Get
                Return Me.laneDropOffTueField
            End Get
            Set
                Me.laneDropOffTueField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffWed() As Boolean
            Get
                Return Me.laneDropOffWedField
            End Get
            Set
                Me.laneDropOffWedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffThu() As Boolean
            Get
                Return Me.laneDropOffThuField
            End Get
            Set
                Me.laneDropOffThuField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffFri() As Boolean
            Get
                Return Me.laneDropOffFriField
            End Get
            Set
                Me.laneDropOffFriField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffSat() As Boolean
            Get
                Return Me.laneDropOffSatField
            End Get
            Set
                Me.laneDropOffSatField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDropOffSun() As Boolean
            Get
                Return Me.laneDropOffSunField
            End Get
            Set
                Me.laneDropOffSunField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDefaultRouteSequence() As Integer
            Get
                Return Me.laneDefaultRouteSequenceField
            End Get
            Set
                Me.laneDefaultRouteSequenceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRouteGuideNumber() As String
            Get
                Return Me.laneRouteGuideNumberField
            End Get
            Set
                Me.laneRouteGuideNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneIsCrossDockFacility() As Boolean
            Get
                Return Me.laneIsCrossDockFacilityField
            End Get
            Set
                Me.laneIsCrossDockFacilityField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsLaneObject70
        Inherits clsLaneObject60
        
        Private laneLegalEntityField As String
        
        Private laneCompAlphaCodeField As String
        
        Private laneRequiredOnTimeServiceLevelField As Decimal
        
        Private laneCalcOnTimeServiceLevelField As Decimal
        
        Private laneCalcOnTimeNoMonthsUsedField As Decimal
        
        Private laneModeTypeControlField As Integer
        
        Private laneUser1Field As String
        
        Private laneUser2Field As String
        
        Private laneUser3Field As String
        
        Private laneUser4Field As String
        
        Private laneOrigLegalEntityField As String
        
        Private laneOrigCompAlphaCodeField As String
        
        Private laneDestLegalEntityField As String
        
        Private laneDestCompAlphaCodeField As String
        
        '''<remarks/>
        Public Property LaneLegalEntity() As String
            Get
                Return Me.laneLegalEntityField
            End Get
            Set
                Me.laneLegalEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCompAlphaCode() As String
            Get
                Return Me.laneCompAlphaCodeField
            End Get
            Set
                Me.laneCompAlphaCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneRequiredOnTimeServiceLevel() As Decimal
            Get
                Return Me.laneRequiredOnTimeServiceLevelField
            End Get
            Set
                Me.laneRequiredOnTimeServiceLevelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCalcOnTimeServiceLevel() As Decimal
            Get
                Return Me.laneCalcOnTimeServiceLevelField
            End Get
            Set
                Me.laneCalcOnTimeServiceLevelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneCalcOnTimeNoMonthsUsed() As Decimal
            Get
                Return Me.laneCalcOnTimeNoMonthsUsedField
            End Get
            Set
                Me.laneCalcOnTimeNoMonthsUsedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneModeTypeControl() As Integer
            Get
                Return Me.laneModeTypeControlField
            End Get
            Set
                Me.laneModeTypeControlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneUser1() As String
            Get
                Return Me.laneUser1Field
            End Get
            Set
                Me.laneUser1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneUser2() As String
            Get
                Return Me.laneUser2Field
            End Get
            Set
                Me.laneUser2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneUser3() As String
            Get
                Return Me.laneUser3Field
            End Get
            Set
                Me.laneUser3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneUser4() As String
            Get
                Return Me.laneUser4Field
            End Get
            Set
                Me.laneUser4Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigLegalEntity() As String
            Get
                Return Me.laneOrigLegalEntityField
            End Get
            Set
                Me.laneOrigLegalEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneOrigCompAlphaCode() As String
            Get
                Return Me.laneOrigCompAlphaCodeField
            End Get
            Set
                Me.laneOrigCompAlphaCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestLegalEntity() As String
            Get
                Return Me.laneDestLegalEntityField
            End Get
            Set
                Me.laneDestLegalEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LaneDestCompAlphaCode() As String
            Get
                Return Me.laneDestCompAlphaCodeField
            End Get
            Set
                Me.laneDestCompAlphaCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsLaneCalendarObject
        
        Private laneNumberField As String
        
        Private monthField As Integer
        
        Private dayField As Integer
        
        Private openField As Boolean
        
        Private startTimeField As String
        
        Private endTimeField As String
        
        Private isHolidayField As Boolean
        
        Private applyToOriginField As Boolean
        
        '''<remarks/>
        Public Property LaneNumber() As String
            Get
                Return Me.laneNumberField
            End Get
            Set
                Me.laneNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Month() As Integer
            Get
                Return Me.monthField
            End Get
            Set
                Me.monthField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Day() As Integer
            Get
                Return Me.dayField
            End Get
            Set
                Me.dayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Open() As Boolean
            Get
                Return Me.openField
            End Get
            Set
                Me.openField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property StartTime() As String
            Get
                Return Me.startTimeField
            End Get
            Set
                Me.startTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EndTime() As String
            Get
                Return Me.endTimeField
            End Get
            Set
                Me.endTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IsHoliday() As Boolean
            Get
                Return Me.isHolidayField
            End Get
            Set
                Me.isHolidayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ApplyToOrigin() As Boolean
            Get
                Return Me.applyToOriginField
            End Get
            Set
                Me.applyToOriginField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LastErrorCompletedEventHandler(ByVal sender As Object, ByVal e As LastErrorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LastErrorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessDataCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessDataExCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessDataExCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessDataExCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ReturnMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessDataWCalendarCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessDataWCalendarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessDataWCalendarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ReturnMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessData60CompletedEventHandler(ByVal sender As Object, ByVal e As ProcessData60CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessData60CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ReturnMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessData60WCalendarCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessData60WCalendarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessData60WCalendarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ReturnMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessData70CompletedEventHandler(ByVal sender As Object, ByVal e As ProcessData70CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessData70CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ReturnMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
