//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NGL.Integration.CSharpSample.NGLCarrierData {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CarrierObjectSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsImportDataBase))]
    public partial class CarrierObject : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LastErrorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessDataExOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessData70OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CarrierObject() {
            this.Url = global::NGL.Integration.CSharpSample.Properties.Settings.Default.NGL_Integration_CSharpSample_NGLCarrierData_CarrierObject;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LastErrorCompletedEventHandler LastErrorCompleted;
        
        /// <remarks/>
        public event ProcessDataCompletedEventHandler ProcessDataCompleted;
        
        /// <remarks/>
        public event ProcessDataExCompletedEventHandler ProcessDataExCompleted;
        
        /// <remarks/>
        public event ProcessData70CompletedEventHandler ProcessData70Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LastError", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LastError() {
            object[] results = this.Invoke("LastError", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LastErrorAsync() {
            this.LastErrorAsync(null);
        }
        
        /// <remarks/>
        public void LastErrorAsync(object userState) {
            if ((this.LastErrorOperationCompleted == null)) {
                this.LastErrorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLastErrorOperationCompleted);
            }
            this.InvokeAsync("LastError", new object[0], this.LastErrorOperationCompleted, userState);
        }
        
        private void OnLastErrorOperationCompleted(object arg) {
            if ((this.LastErrorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LastErrorCompleted(this, new LastErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProcessData(string AuthorizationCode, clsCarrierHeaderObject[] CarrierHeaders, clsCarrierContactObject[] CarrierContacts) {
            object[] results = this.Invoke("ProcessData", new object[] {
                        AuthorizationCode,
                        CarrierHeaders,
                        CarrierContacts});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDataAsync(string AuthorizationCode, clsCarrierHeaderObject[] CarrierHeaders, clsCarrierContactObject[] CarrierContacts) {
            this.ProcessDataAsync(AuthorizationCode, CarrierHeaders, CarrierContacts, null);
        }
        
        /// <remarks/>
        public void ProcessDataAsync(string AuthorizationCode, clsCarrierHeaderObject[] CarrierHeaders, clsCarrierContactObject[] CarrierContacts, object userState) {
            if ((this.ProcessDataOperationCompleted == null)) {
                this.ProcessDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDataOperationCompleted);
            }
            this.InvokeAsync("ProcessData", new object[] {
                        AuthorizationCode,
                        CarrierHeaders,
                        CarrierContacts}, this.ProcessDataOperationCompleted, userState);
        }
        
        private void OnProcessDataOperationCompleted(object arg) {
            if ((this.ProcessDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDataCompleted(this, new ProcessDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessDataEx", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProcessDataEx(string AuthorizationCode, clsCarrierHeaderObject[] CarrierHeaders, clsCarrierContactObject[] CarrierContacts, ref string ReturnMessage) {
            object[] results = this.Invoke("ProcessDataEx", new object[] {
                        AuthorizationCode,
                        CarrierHeaders,
                        CarrierContacts,
                        ReturnMessage});
            ReturnMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessDataExAsync(string AuthorizationCode, clsCarrierHeaderObject[] CarrierHeaders, clsCarrierContactObject[] CarrierContacts, string ReturnMessage) {
            this.ProcessDataExAsync(AuthorizationCode, CarrierHeaders, CarrierContacts, ReturnMessage, null);
        }
        
        /// <remarks/>
        public void ProcessDataExAsync(string AuthorizationCode, clsCarrierHeaderObject[] CarrierHeaders, clsCarrierContactObject[] CarrierContacts, string ReturnMessage, object userState) {
            if ((this.ProcessDataExOperationCompleted == null)) {
                this.ProcessDataExOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessDataExOperationCompleted);
            }
            this.InvokeAsync("ProcessDataEx", new object[] {
                        AuthorizationCode,
                        CarrierHeaders,
                        CarrierContacts,
                        ReturnMessage}, this.ProcessDataExOperationCompleted, userState);
        }
        
        private void OnProcessDataExOperationCompleted(object arg) {
            if ((this.ProcessDataExCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessDataExCompleted(this, new ProcessDataExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData70", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ProcessData70(string AuthorizationCode, clsCarrierHeaderObject70[] CarrierHeaders, clsCarrierContactObject70[] CarrierContacts, ref string ReturnMessage) {
            object[] results = this.Invoke("ProcessData70", new object[] {
                        AuthorizationCode,
                        CarrierHeaders,
                        CarrierContacts,
                        ReturnMessage});
            ReturnMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessData70Async(string AuthorizationCode, clsCarrierHeaderObject70[] CarrierHeaders, clsCarrierContactObject70[] CarrierContacts, string ReturnMessage) {
            this.ProcessData70Async(AuthorizationCode, CarrierHeaders, CarrierContacts, ReturnMessage, null);
        }
        
        /// <remarks/>
        public void ProcessData70Async(string AuthorizationCode, clsCarrierHeaderObject70[] CarrierHeaders, clsCarrierContactObject70[] CarrierContacts, string ReturnMessage, object userState) {
            if ((this.ProcessData70OperationCompleted == null)) {
                this.ProcessData70OperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessData70OperationCompleted);
            }
            this.InvokeAsync("ProcessData70", new object[] {
                        AuthorizationCode,
                        CarrierHeaders,
                        CarrierContacts,
                        ReturnMessage}, this.ProcessData70OperationCompleted, userState);
        }
        
        private void OnProcessData70OperationCompleted(object arg) {
            if ((this.ProcessData70Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessData70Completed(this, new ProcessData70CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsCarrierHeaderObject {
        
        private int carrierNumberField;
        
        private string carrierNameField;
        
        private string carrierStreetAddress1Field;
        
        private string carrierStreetAddress2Field;
        
        private string carrierStreetAddress3Field;
        
        private string carrierStreetCityField;
        
        private string carrierStreetStateField;
        
        private string carrierStreetCountryField;
        
        private string carrierStreetZipField;
        
        private string carrierMailAddress1Field;
        
        private string carrierMailAddress2Field;
        
        private string carrierMailAddress3Field;
        
        private string carrierMailCityField;
        
        private string carrierMailStateField;
        
        private string carrierMailCountryField;
        
        private string carrierMailZipField;
        
        private string carrierTypeCodeField;
        
        private string carrierSCACField;
        
        private string carrierWebSiteField;
        
        private string carrierEmailField;
        
        private string carrierQualInsuranceDateField;
        
        private bool carrierQualQualifiedField;
        
        private string carrierQualAuthorityField;
        
        private bool carrierQualContractField;
        
        private string carrierQualSignedDateField;
        
        private string carrierQualContractExpiresDateField;
        
        /// <remarks/>
        public int CarrierNumber {
            get {
                return this.carrierNumberField;
            }
            set {
                this.carrierNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierName {
            get {
                return this.carrierNameField;
            }
            set {
                this.carrierNameField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetAddress1 {
            get {
                return this.carrierStreetAddress1Field;
            }
            set {
                this.carrierStreetAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetAddress2 {
            get {
                return this.carrierStreetAddress2Field;
            }
            set {
                this.carrierStreetAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetAddress3 {
            get {
                return this.carrierStreetAddress3Field;
            }
            set {
                this.carrierStreetAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetCity {
            get {
                return this.carrierStreetCityField;
            }
            set {
                this.carrierStreetCityField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetState {
            get {
                return this.carrierStreetStateField;
            }
            set {
                this.carrierStreetStateField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetCountry {
            get {
                return this.carrierStreetCountryField;
            }
            set {
                this.carrierStreetCountryField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetZip {
            get {
                return this.carrierStreetZipField;
            }
            set {
                this.carrierStreetZipField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailAddress1 {
            get {
                return this.carrierMailAddress1Field;
            }
            set {
                this.carrierMailAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailAddress2 {
            get {
                return this.carrierMailAddress2Field;
            }
            set {
                this.carrierMailAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailAddress3 {
            get {
                return this.carrierMailAddress3Field;
            }
            set {
                this.carrierMailAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailCity {
            get {
                return this.carrierMailCityField;
            }
            set {
                this.carrierMailCityField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailState {
            get {
                return this.carrierMailStateField;
            }
            set {
                this.carrierMailStateField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailCountry {
            get {
                return this.carrierMailCountryField;
            }
            set {
                this.carrierMailCountryField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailZip {
            get {
                return this.carrierMailZipField;
            }
            set {
                this.carrierMailZipField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierTypeCode {
            get {
                return this.carrierTypeCodeField;
            }
            set {
                this.carrierTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierSCAC {
            get {
                return this.carrierSCACField;
            }
            set {
                this.carrierSCACField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierWebSite {
            get {
                return this.carrierWebSiteField;
            }
            set {
                this.carrierWebSiteField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierEmail {
            get {
                return this.carrierEmailField;
            }
            set {
                this.carrierEmailField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualInsuranceDate {
            get {
                return this.carrierQualInsuranceDateField;
            }
            set {
                this.carrierQualInsuranceDateField = value;
            }
        }
        
        /// <remarks/>
        public bool CarrierQualQualified {
            get {
                return this.carrierQualQualifiedField;
            }
            set {
                this.carrierQualQualifiedField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualAuthority {
            get {
                return this.carrierQualAuthorityField;
            }
            set {
                this.carrierQualAuthorityField = value;
            }
        }
        
        /// <remarks/>
        public bool CarrierQualContract {
            get {
                return this.carrierQualContractField;
            }
            set {
                this.carrierQualContractField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualSignedDate {
            get {
                return this.carrierQualSignedDateField;
            }
            set {
                this.carrierQualSignedDateField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualContractExpiresDate {
            get {
                return this.carrierQualContractExpiresDateField;
            }
            set {
                this.carrierQualContractExpiresDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsCarrierContactObject70))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(clsCarrierHeaderObject70))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsImportDataBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsCarrierContactObject70 : clsImportDataBase {
        
        private string carrierLegalEntityField;
        
        private int carrierNumberField;
        
        private string carrierAlphaCodeField;
        
        private string carrierContNameField;
        
        private string carrierContTitleField;
        
        private string carrierContactPhoneField;
        
        private string carrierContPhoneExtField;
        
        private string carrierContactFaxField;
        
        private string carrierContact800Field;
        
        private string carrierContactEMailField;
        
        /// <remarks/>
        public string CarrierLegalEntity {
            get {
                return this.carrierLegalEntityField;
            }
            set {
                this.carrierLegalEntityField = value;
            }
        }
        
        /// <remarks/>
        public int CarrierNumber {
            get {
                return this.carrierNumberField;
            }
            set {
                this.carrierNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierAlphaCode {
            get {
                return this.carrierAlphaCodeField;
            }
            set {
                this.carrierAlphaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContName {
            get {
                return this.carrierContNameField;
            }
            set {
                this.carrierContNameField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContTitle {
            get {
                return this.carrierContTitleField;
            }
            set {
                this.carrierContTitleField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContactPhone {
            get {
                return this.carrierContactPhoneField;
            }
            set {
                this.carrierContactPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContPhoneExt {
            get {
                return this.carrierContPhoneExtField;
            }
            set {
                this.carrierContPhoneExtField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContactFax {
            get {
                return this.carrierContactFaxField;
            }
            set {
                this.carrierContactFaxField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContact800 {
            get {
                return this.carrierContact800Field;
            }
            set {
                this.carrierContact800Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContactEMail {
            get {
                return this.carrierContactEMailField;
            }
            set {
                this.carrierContactEMailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsCarrierHeaderObject70 : clsImportDataBase {
        
        private string carrierLegalEntityField;
        
        private int carrierNumberField;
        
        private string carrierAlphaCodeField;
        
        private string carrierNameField;
        
        private string carrierStreetAddress1Field;
        
        private string carrierStreetAddress2Field;
        
        private string carrierStreetAddress3Field;
        
        private string carrierStreetCityField;
        
        private string carrierStreetStateField;
        
        private string carrierStreetCountryField;
        
        private string carrierStreetZipField;
        
        private string carrierMailAddress1Field;
        
        private string carrierMailAddress2Field;
        
        private string carrierMailAddress3Field;
        
        private string carrierMailCityField;
        
        private string carrierMailStateField;
        
        private string carrierMailCountryField;
        
        private string carrierMailZipField;
        
        private string carrierTypeCodeField;
        
        private string carrierSCACField;
        
        private string carrierWebSiteField;
        
        private string carrierEmailField;
        
        private string carrierQualInsuranceDateField;
        
        private bool carrierQualQualifiedField;
        
        private string carrierQualAuthorityField;
        
        private bool carrierQualContractField;
        
        private string carrierQualSignedDateField;
        
        private string carrierQualContractExpiresDateField;
        
        private string carrierCurrencyTypeField;
        
        private string carrierUser1Field;
        
        private string carrierUser2Field;
        
        private string carrierUser3Field;
        
        private string carrierUser4Field;
        
        /// <remarks/>
        public string CarrierLegalEntity {
            get {
                return this.carrierLegalEntityField;
            }
            set {
                this.carrierLegalEntityField = value;
            }
        }
        
        /// <remarks/>
        public int CarrierNumber {
            get {
                return this.carrierNumberField;
            }
            set {
                this.carrierNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierAlphaCode {
            get {
                return this.carrierAlphaCodeField;
            }
            set {
                this.carrierAlphaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierName {
            get {
                return this.carrierNameField;
            }
            set {
                this.carrierNameField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetAddress1 {
            get {
                return this.carrierStreetAddress1Field;
            }
            set {
                this.carrierStreetAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetAddress2 {
            get {
                return this.carrierStreetAddress2Field;
            }
            set {
                this.carrierStreetAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetAddress3 {
            get {
                return this.carrierStreetAddress3Field;
            }
            set {
                this.carrierStreetAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetCity {
            get {
                return this.carrierStreetCityField;
            }
            set {
                this.carrierStreetCityField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetState {
            get {
                return this.carrierStreetStateField;
            }
            set {
                this.carrierStreetStateField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetCountry {
            get {
                return this.carrierStreetCountryField;
            }
            set {
                this.carrierStreetCountryField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierStreetZip {
            get {
                return this.carrierStreetZipField;
            }
            set {
                this.carrierStreetZipField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailAddress1 {
            get {
                return this.carrierMailAddress1Field;
            }
            set {
                this.carrierMailAddress1Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailAddress2 {
            get {
                return this.carrierMailAddress2Field;
            }
            set {
                this.carrierMailAddress2Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailAddress3 {
            get {
                return this.carrierMailAddress3Field;
            }
            set {
                this.carrierMailAddress3Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailCity {
            get {
                return this.carrierMailCityField;
            }
            set {
                this.carrierMailCityField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailState {
            get {
                return this.carrierMailStateField;
            }
            set {
                this.carrierMailStateField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailCountry {
            get {
                return this.carrierMailCountryField;
            }
            set {
                this.carrierMailCountryField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierMailZip {
            get {
                return this.carrierMailZipField;
            }
            set {
                this.carrierMailZipField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierTypeCode {
            get {
                return this.carrierTypeCodeField;
            }
            set {
                this.carrierTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierSCAC {
            get {
                return this.carrierSCACField;
            }
            set {
                this.carrierSCACField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierWebSite {
            get {
                return this.carrierWebSiteField;
            }
            set {
                this.carrierWebSiteField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierEmail {
            get {
                return this.carrierEmailField;
            }
            set {
                this.carrierEmailField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualInsuranceDate {
            get {
                return this.carrierQualInsuranceDateField;
            }
            set {
                this.carrierQualInsuranceDateField = value;
            }
        }
        
        /// <remarks/>
        public bool CarrierQualQualified {
            get {
                return this.carrierQualQualifiedField;
            }
            set {
                this.carrierQualQualifiedField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualAuthority {
            get {
                return this.carrierQualAuthorityField;
            }
            set {
                this.carrierQualAuthorityField = value;
            }
        }
        
        /// <remarks/>
        public bool CarrierQualContract {
            get {
                return this.carrierQualContractField;
            }
            set {
                this.carrierQualContractField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualSignedDate {
            get {
                return this.carrierQualSignedDateField;
            }
            set {
                this.carrierQualSignedDateField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierQualContractExpiresDate {
            get {
                return this.carrierQualContractExpiresDateField;
            }
            set {
                this.carrierQualContractExpiresDateField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierCurrencyType {
            get {
                return this.carrierCurrencyTypeField;
            }
            set {
                this.carrierCurrencyTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierUser1 {
            get {
                return this.carrierUser1Field;
            }
            set {
                this.carrierUser1Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierUser2 {
            get {
                return this.carrierUser2Field;
            }
            set {
                this.carrierUser2Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierUser3 {
            get {
                return this.carrierUser3Field;
            }
            set {
                this.carrierUser3Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierUser4 {
            get {
                return this.carrierUser4Field;
            }
            set {
                this.carrierUser4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class clsCarrierContactObject {
        
        private int carrierNumberField;
        
        private string carrierContNameField;
        
        private string carrierContTitleField;
        
        private string carrierContactPhoneField;
        
        private string carrierContactFaxField;
        
        private string carrierContact800Field;
        
        private string carrierContactEMailField;
        
        /// <remarks/>
        public int CarrierNumber {
            get {
                return this.carrierNumberField;
            }
            set {
                this.carrierNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContName {
            get {
                return this.carrierContNameField;
            }
            set {
                this.carrierContNameField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContTitle {
            get {
                return this.carrierContTitleField;
            }
            set {
                this.carrierContTitleField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContactPhone {
            get {
                return this.carrierContactPhoneField;
            }
            set {
                this.carrierContactPhoneField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContactFax {
            get {
                return this.carrierContactFaxField;
            }
            set {
                this.carrierContactFaxField = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContact800 {
            get {
                return this.carrierContact800Field;
            }
            set {
                this.carrierContact800Field = value;
            }
        }
        
        /// <remarks/>
        public string CarrierContactEMail {
            get {
                return this.carrierContactEMailField;
            }
            set {
                this.carrierContactEMailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LastErrorCompletedEventHandler(object sender, LastErrorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LastErrorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LastErrorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ProcessDataCompletedEventHandler(object sender, ProcessDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ProcessDataExCompletedEventHandler(object sender, ProcessDataExCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessDataExCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessDataExCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void ProcessData70CompletedEventHandler(object sender, ProcessData70CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessData70CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessData70CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ReturnMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591