'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://tonto.eia.doe.gov/oog/info/wohdp/diesel_detail_report_combined.asp")>  _
        Public Property EIADieselPricesURL() As String
            Get
                Return CType(Me("EIADieselPricesURL"),String)
            End Get
            Set
                Me("EIADieselPricesURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property GetFuelByXLS() As Boolean
            Get
                Return CType(Me("GetFuelByXLS"),Boolean)
            End Get
            Set
                Me("GetFuelByXLS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.eia.gov/petroleum/gasdiesel/xls/psw18vwall.xls")>  _
        Public Property EIADieselPricesURL_XLS() As String
            Get
                Return CType(Me("EIADieselPricesURL_XLS"),String)
            End Get
            Set
                Me("EIADieselPricesURL_XLS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data 1")>  _
        Public Property WorkSheetName() As String
            Get
                Return CType(Me("WorkSheetName"),String)
            End Get
            Set
                Me("WorkSheetName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_NUS_DPG")>  _
        Public Property WklyUSKey() As String
            Get
                Return CType(Me("WklyUSKey"),String)
            End Get
            Set
                Me("WklyUSKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R10_DPG")>  _
        Public Property WklyEastCoastKey() As String
            Get
                Return CType(Me("WklyEastCoastKey"),String)
            End Get
            Set
                Me("WklyEastCoastKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R1X_DPG")>  _
        Public Property WklyNewEnglandKey() As String
            Get
                Return CType(Me("WklyNewEnglandKey"),String)
            End Get
            Set
                Me("WklyNewEnglandKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R1Y_DPG")>  _
        Public Property WklyCentralAtlanticKey() As String
            Get
                Return CType(Me("WklyCentralAtlanticKey"),String)
            End Get
            Set
                Me("WklyCentralAtlanticKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R1Z_DPG")>  _
        Public Property WklyLowerAtlanticKey() As String
            Get
                Return CType(Me("WklyLowerAtlanticKey"),String)
            End Get
            Set
                Me("WklyLowerAtlanticKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R20_DPG")>  _
        Public Property WklyMidWestKey() As String
            Get
                Return CType(Me("WklyMidWestKey"),String)
            End Get
            Set
                Me("WklyMidWestKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R30_DPG")>  _
        Public Property WklyGulfCoastKey() As String
            Get
                Return CType(Me("WklyGulfCoastKey"),String)
            End Get
            Set
                Me("WklyGulfCoastKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R40_DPG")>  _
        Public Property WklyRockeyMTNKey() As String
            Get
                Return CType(Me("WklyRockeyMTNKey"),String)
            End Get
            Set
                Me("WklyRockeyMTNKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_R50_DPG")>  _
        Public Property WklyWestCoastKey() As String
            Get
                Return CType(Me("WklyWestCoastKey"),String)
            End Get
            Set
                Me("WklyWestCoastKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("EMD_EPD2D_PTE_SCA_DPG")>  _
        Public Property WklkCaliforniaKey() As String
            Get
                Return CType(Me("WklkCaliforniaKey"),String)
            End Get
            Set
                Me("WklkCaliforniaKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sourcekey")>  _
        Public Property SourceKeyStr() As String
            Get
                Return CType(Me("SourceKeyStr"),String)
            End Get
            Set
                Me("SourceKeyStr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property GetWeeksBack() As Integer
            Get
                Return CType(Me("GetWeeksBack"),Integer)
            End Get
            Set
                Me("GetWeeksBack") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info@maxximu.com")>  _
        Public Property AdminEmail() As String
            Get
                Return CType(Me("AdminEmail"),String)
            End Get
            Set
                Me("AdminEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info@maxximu.com")>  _
        Public Property GroupEmail() As String
            Get
                Return CType(Me("GroupEmail"),String)
            End Get
            Set
                Me("GroupEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info@maxximu.com")>  _
        Public Property FromEmail() As String
            Get
                Return CType(Me("FromEmail"),String)
            End Get
            Set
                Me("FromEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")>  _
        Public Property SMTPServer() As String
            Get
                Return CType(Me("SMTPServer"),String)
            End Get
            Set
                Me("SMTPServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SaveOldLog() As Boolean
            Get
                Return CType(Me("SaveOldLog"),Boolean)
            End Get
            Set
                Me("SaveOldLog") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property KeepLogDays() As Integer
            Get
                Return CType(Me("KeepLogDays"),Integer)
            End Get
            Set
                Me("KeepLogDays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("info@maxximu.com")>  _
        Public Property GlobalFuelIndexUpdateEmailNotification() As String
            Get
                Return CType(Me("GlobalFuelIndexUpdateEmailNotification"),String)
            End Get
            Set
                Me("GlobalFuelIndexUpdateEmailNotification") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property GlobalFuelIndexUpdateEmailNotificationValue() As Boolean
            Get
                Return CType(Me("GlobalFuelIndexUpdateEmailNotificationValue"),Boolean)
            End Get
            Set
                Me("GlobalFuelIndexUpdateEmailNotificationValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Use48Mode() As Boolean
            Get
                Return CType(Me("Use48Mode"),Boolean)
            End Get
            Set
                Me("Use48Mode") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.NGL.FM.CMDLine.FuelIndexUpdater.My.MySettings
            Get
                Return Global.NGL.FM.CMDLine.FuelIndexUpdater.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
