//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.FM.CMDLine.D365Integration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.dynamicstms365.com/ws/DTMSIntegration.asmx")]
        public string NGL_FM_CMDLine_D365Integration_TMSIntegrationSettings_DTMSIntegration {
            get {
                return ((string)(this["NGL_FM_CMDLine_D365Integration_TMSIntegrationSettings_DTMSIntegration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.dynamicstms365.com/ws/DTMSERPIntegration.asmx")]
        public string NGL_FM_CMDLine_D365Integration_TMSIntegrationServices_DTMSERPIntegration {
            get {
                return ((string)(this["NGL_FM_CMDLine_D365Integration_TMSIntegrationServices_DTMSERPIntegration"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ngl-dev015e64cfd23d55673cdevaos.axcloud.dynamics.com/")]
        public string D365_URL {
            get {
                return ((string)(this["D365_URL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sts.windows.net/2518be7e-c933-4905-af64-24ad0157202f")]
        public string ActiveDirectoryTenant {
            get {
                return ((string)(this["ActiveDirectoryTenant"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f065bd6b-2455-4963-a00b-d205c095c461")]
        public string ActiveDirectoryClientAppId {
            get {
                return ((string)(this["ActiveDirectoryClientAppId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0bF7Q~mPdDfMJfC9FkJf4N.fM5NTUrzVJaz45")]
        public string ActiveDirectoryClientAppSecret {
            get {
                return ((string)(this["ActiveDirectoryClientAppSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://ngl-dev015e64cfd23d55673cdevaos.axcloud.dynamics.com")]
        public string ActiveDirectoryResource {
            get {
                return ((string)(this["ActiveDirectoryResource"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USMF")]
        public string LegalEntities {
            get {
                return ((string)(this["LegalEntities"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WSPROD")]
        public string DTMSAuthCode {
            get {
                return ((string)(this["DTMSAuthCode"]));
            }
        }
    }
}
