'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/BookObject.asmx")>  _
        Public Property DTMSTestWebServices_NGLBookObjectWS_BookObject() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLBookObjectWS_BookObject"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLBookObjectWS_BookObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/LaneObject.asmx")>  _
        Public Property DTMSTestWebServices_NGLLaneObjectWS_LaneObject() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLLaneObjectWS_LaneObject"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLLaneObjectWS_LaneObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/CarrierObject.asmx")>  _
        Public Property DTMSTestWebServices_NGLCarrierObjectWS_CarrierObject() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLCarrierObjectWS_CarrierObject"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLCarrierObjectWS_CarrierObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/CompanyObject.asmx")>  _
        Public Property DTMSTestWebServices_NGLCompanyObjectWS_CompanyObject() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLCompanyObjectWS_CompanyObject"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLCompanyObjectWS_CompanyObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/APExportObject.asmx")>  _
        Public Property DTMSTestWebServices_NGLAPExportObjectWS_APExportObject() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLAPExportObjectWS_APExportObject"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLAPExportObjectWS_APExportObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/PayablesObject.asmx")>  _
        Public Property DTMSTestWebServices_NGLPayablesObjectWS_PayablesObject() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLPayablesObjectWS_PayablesObject"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLPayablesObjectWS_PayablesObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/PickListObject.asmx")>  _
        Public Property DTMSTestWebServices_NGLPickListObjectWS_PickListObject() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLPickListObjectWS_PickListObject"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLPickListObjectWS_PickListObject") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://07dws.nextgeneration.com/DTMSERPIntegration.asmx")>  _
        Public Property DTMSTestWebServices_NGLDTMSERPIntegrationWS_DTMSERPIntegration() As String
            Get
                Return CType(Me("DTMSTestWebServices_NGLDTMSERPIntegrationWS_DTMSERPIntegration"),String)
            End Get
            Set
                Me("DTMSTestWebServices_NGLDTMSERPIntegrationWS_DTMSERPIntegration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NGLWSTEST")>  _
        Public Property AuthCode() As String
            Get
                Return CType(Me("AuthCode"),String)
            End Get
            Set
                Me("AuthCode") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DTMSTestWebServices.My.MySettings
            Get
                Return Global.DTMSTestWebServices.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
