//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGL.Integration.CSharpSample.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nglwsdev70.nextgeneration.com/BookObject.asmx")]
        public string NGL_Integration_CSharpSample_NGLBookData_BookObject {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_NGLBookData_BookObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nglwsdev704.nextgeneration.com/companyobject.asmx")]
        public string NGL_Integration_CSharpSample_NGLCompanyData_CompanyObject {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_NGLCompanyData_CompanyObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nglwsdev704.nextgeneration.com/CarrierObject.asmx")]
        public string NGL_Integration_CSharpSample_NGLCarrierData_CarrierObject {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_NGLCarrierData_CarrierObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nglwsdev704.nextgeneration.com/LaneObject.asmx")]
        public string NGL_Integration_CSharpSample_NGLLaneData_LaneObject {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_NGLLaneData_LaneObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nglwsdev704.nextgeneration.com/PickListObject.asmx")]
        public string NGL_Integration_CSharpSample_NGLPickListData_PickListObject {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_NGLPickListData_PickListObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nglwsdev704.nextgeneration.com/apexportobject.asmx")]
        public string NGL_Integration_CSharpSample_NGLAPExportData_APExportObject {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_NGLAPExportData_APExportObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:55503/bookobject.asmx")]
        public string NGL_Integration_CSharpSample_NGLBookData6044m_BookObject {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_NGLBookData6044m_BookObject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:44320/ws/DTMSERPIntegration.asmx")]
        public string NGL_Integration_CSharpSample_DTMSIntegration_DTMSERPIntegration {
            get {
                return ((string)(this["NGL_Integration_CSharpSample_DTMSIntegration_DTMSERPIntegration"]));
            }
        }
    }
}
