'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace NGLScheduleObjectWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ScheduleObjectSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(clsImportDataBase))>  _
    Partial Public Class ScheduleObject
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private LastErrorOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessDataOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessDataExOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ProcessData70OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.IntegrationAssembliesTesting.My.MySettings.Default.IntegrationAssembliesTesting_NGLScheduleObjectWebService_ScheduleObject
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event LastErrorCompleted As LastErrorCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessDataCompleted As ProcessDataCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessDataExCompleted As ProcessDataExCompletedEventHandler
        
        '''<remarks/>
        Public Event ProcessData70Completed As ProcessData70CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LastError", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LastError() As String
            Dim results() As Object = Me.Invoke("LastError", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LastErrorAsync()
            Me.LastErrorAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LastErrorAsync(ByVal userState As Object)
            If (Me.LastErrorOperationCompleted Is Nothing) Then
                Me.LastErrorOperationCompleted = AddressOf Me.OnLastErrorOperationCompleted
            End If
            Me.InvokeAsync("LastError", New Object(-1) {}, Me.LastErrorOperationCompleted, userState)
        End Sub
        
        Private Sub OnLastErrorOperationCompleted(ByVal arg As Object)
            If (Not (Me.LastErrorCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LastErrorCompleted(Me, New LastErrorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessData(ByVal AuthorizationCode As String, ByVal Schedules() As clsScheduleObject) As Integer
            Dim results() As Object = Me.Invoke("ProcessData", New Object() {AuthorizationCode, Schedules})
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessDataAsync(ByVal AuthorizationCode As String, ByVal Schedules() As clsScheduleObject)
            Me.ProcessDataAsync(AuthorizationCode, Schedules, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessDataAsync(ByVal AuthorizationCode As String, ByVal Schedules() As clsScheduleObject, ByVal userState As Object)
            If (Me.ProcessDataOperationCompleted Is Nothing) Then
                Me.ProcessDataOperationCompleted = AddressOf Me.OnProcessDataOperationCompleted
            End If
            Me.InvokeAsync("ProcessData", New Object() {AuthorizationCode, Schedules}, Me.ProcessDataOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessDataOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessDataCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessDataCompleted(Me, New ProcessDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessDataEx", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessDataEx(ByVal AuthorizationCode As String, ByVal Schedules() As clsScheduleObject, ByRef ReturnMessage As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessDataEx", New Object() {AuthorizationCode, Schedules, ReturnMessage})
            ReturnMessage = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessDataExAsync(ByVal AuthorizationCode As String, ByVal Schedules() As clsScheduleObject, ByVal ReturnMessage As String)
            Me.ProcessDataExAsync(AuthorizationCode, Schedules, ReturnMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessDataExAsync(ByVal AuthorizationCode As String, ByVal Schedules() As clsScheduleObject, ByVal ReturnMessage As String, ByVal userState As Object)
            If (Me.ProcessDataExOperationCompleted Is Nothing) Then
                Me.ProcessDataExOperationCompleted = AddressOf Me.OnProcessDataExOperationCompleted
            End If
            Me.InvokeAsync("ProcessDataEx", New Object() {AuthorizationCode, Schedules, ReturnMessage}, Me.ProcessDataExOperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessDataExOperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessDataExCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessDataExCompleted(Me, New ProcessDataExCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessData70", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ProcessData70(ByVal AuthorizationCode As String, ByVal Schedule() As clsScheduleObject70, ByRef ReturnMessage As String) As Integer
            Dim results() As Object = Me.Invoke("ProcessData70", New Object() {AuthorizationCode, Schedule, ReturnMessage})
            ReturnMessage = CType(results(1),String)
            Return CType(results(0),Integer)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ProcessData70Async(ByVal AuthorizationCode As String, ByVal Schedule() As clsScheduleObject70, ByVal ReturnMessage As String)
            Me.ProcessData70Async(AuthorizationCode, Schedule, ReturnMessage, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ProcessData70Async(ByVal AuthorizationCode As String, ByVal Schedule() As clsScheduleObject70, ByVal ReturnMessage As String, ByVal userState As Object)
            If (Me.ProcessData70OperationCompleted Is Nothing) Then
                Me.ProcessData70OperationCompleted = AddressOf Me.OnProcessData70OperationCompleted
            End If
            Me.InvokeAsync("ProcessData70", New Object() {AuthorizationCode, Schedule, ReturnMessage}, Me.ProcessData70OperationCompleted, userState)
        End Sub
        
        Private Sub OnProcessData70OperationCompleted(ByVal arg As Object)
            If (Not (Me.ProcessData70CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ProcessData70Completed(Me, New ProcessData70CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsScheduleObject
        
        Private bookCarrOrderNumberField As String
        
        Private bookCarrDockPUAssigmentField As String
        
        Private bookCarrScheduleDateField As String
        
        Private bookCarrScheduleTimeField As String
        
        Private bookCarrActualDateField As String
        
        Private bookCarrActualTimeField As String
        
        Private bookCarrActLoadCompleteDateField As String
        
        Private bookCarrActLoadCompleteTimeField As String
        
        Private compNumberField As String
        
        Private bookPRONumberField As String
        
        Private bookOrderSequenceField As Integer
        
        Private bookCarrStartLoadingDateField As String
        
        Private bookCarrStartLoadingTimeField As String
        
        Private bookCarrFinishLoadingDateField As String
        
        Private bookCarrFinishLoadingTimeField As String
        
        Private bookCarrDockDelAssignmentField As String
        
        Private bookCarrApptDateField As String
        
        Private bookCarrApptTimeField As String
        
        Private bookCarrActDateField As String
        
        Private bookCarrActTimeField As String
        
        Private bookCarrStartUnloadingDateField As String
        
        Private bookCarrStartUnloadingTimeField As String
        
        Private bookCarrFinishUnloadingDateField As String
        
        Private bookCarrFinishUnloadingTimeField As String
        
        Private bookCarrActUnloadCompDateField As String
        
        Private bookCarrActUnloadCompTimeField As String
        
        Private bookShipCarrierNameField As String
        
        Private bookShipCarrierProNumberField As String
        
        Private bookShipCarrierNumberField As String
        
        '''<remarks/>
        Public Property BookCarrOrderNumber() As String
            Get
                Return Me.bookCarrOrderNumberField
            End Get
            Set
                Me.bookCarrOrderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrDockPUAssigment() As String
            Get
                Return Me.bookCarrDockPUAssigmentField
            End Get
            Set
                Me.bookCarrDockPUAssigmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrScheduleDate() As String
            Get
                Return Me.bookCarrScheduleDateField
            End Get
            Set
                Me.bookCarrScheduleDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrScheduleTime() As String
            Get
                Return Me.bookCarrScheduleTimeField
            End Get
            Set
                Me.bookCarrScheduleTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActualDate() As String
            Get
                Return Me.bookCarrActualDateField
            End Get
            Set
                Me.bookCarrActualDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActualTime() As String
            Get
                Return Me.bookCarrActualTimeField
            End Get
            Set
                Me.bookCarrActualTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActLoadCompleteDate() As String
            Get
                Return Me.bookCarrActLoadCompleteDateField
            End Get
            Set
                Me.bookCarrActLoadCompleteDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActLoadCompleteTime() As String
            Get
                Return Me.bookCarrActLoadCompleteTimeField
            End Get
            Set
                Me.bookCarrActLoadCompleteTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompNumber() As String
            Get
                Return Me.compNumberField
            End Get
            Set
                Me.compNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookPRONumber() As String
            Get
                Return Me.bookPRONumberField
            End Get
            Set
                Me.bookPRONumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookOrderSequence() As Integer
            Get
                Return Me.bookOrderSequenceField
            End Get
            Set
                Me.bookOrderSequenceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartLoadingDate() As String
            Get
                Return Me.bookCarrStartLoadingDateField
            End Get
            Set
                Me.bookCarrStartLoadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartLoadingTime() As String
            Get
                Return Me.bookCarrStartLoadingTimeField
            End Get
            Set
                Me.bookCarrStartLoadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishLoadingDate() As String
            Get
                Return Me.bookCarrFinishLoadingDateField
            End Get
            Set
                Me.bookCarrFinishLoadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishLoadingTime() As String
            Get
                Return Me.bookCarrFinishLoadingTimeField
            End Get
            Set
                Me.bookCarrFinishLoadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrDockDelAssignment() As String
            Get
                Return Me.bookCarrDockDelAssignmentField
            End Get
            Set
                Me.bookCarrDockDelAssignmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrApptDate() As String
            Get
                Return Me.bookCarrApptDateField
            End Get
            Set
                Me.bookCarrApptDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrApptTime() As String
            Get
                Return Me.bookCarrApptTimeField
            End Get
            Set
                Me.bookCarrApptTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActDate() As String
            Get
                Return Me.bookCarrActDateField
            End Get
            Set
                Me.bookCarrActDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActTime() As String
            Get
                Return Me.bookCarrActTimeField
            End Get
            Set
                Me.bookCarrActTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartUnloadingDate() As String
            Get
                Return Me.bookCarrStartUnloadingDateField
            End Get
            Set
                Me.bookCarrStartUnloadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartUnloadingTime() As String
            Get
                Return Me.bookCarrStartUnloadingTimeField
            End Get
            Set
                Me.bookCarrStartUnloadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishUnloadingDate() As String
            Get
                Return Me.bookCarrFinishUnloadingDateField
            End Get
            Set
                Me.bookCarrFinishUnloadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishUnloadingTime() As String
            Get
                Return Me.bookCarrFinishUnloadingTimeField
            End Get
            Set
                Me.bookCarrFinishUnloadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActUnloadCompDate() As String
            Get
                Return Me.bookCarrActUnloadCompDateField
            End Get
            Set
                Me.bookCarrActUnloadCompDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActUnloadCompTime() As String
            Get
                Return Me.bookCarrActUnloadCompTimeField
            End Get
            Set
                Me.bookCarrActUnloadCompTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookShipCarrierName() As String
            Get
                Return Me.bookShipCarrierNameField
            End Get
            Set
                Me.bookShipCarrierNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookShipCarrierProNumber() As String
            Get
                Return Me.bookShipCarrierProNumberField
            End Get
            Set
                Me.bookShipCarrierProNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookShipCarrierNumber() As String
            Get
                Return Me.bookShipCarrierNumberField
            End Get
            Set
                Me.bookShipCarrierNumberField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(clsScheduleObject70)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsImportDataBase
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class clsScheduleObject70
        Inherits clsImportDataBase
        
        Private bookCarrOrderNumberField As String
        
        Private bookCarrDockPUAssigmentField As String
        
        Private bookCarrScheduleDateField As String
        
        Private bookCarrScheduleTimeField As String
        
        Private bookCarrActualDateField As String
        
        Private bookCarrActualTimeField As String
        
        Private bookCarrActLoadCompleteDateField As String
        
        Private bookCarrActLoadCompleteTimeField As String
        
        Private compNumberField As String
        
        Private bookPRONumberField As String
        
        Private bookOrderSequenceField As Integer
        
        Private bookCarrStartLoadingDateField As String
        
        Private bookCarrStartLoadingTimeField As String
        
        Private bookCarrFinishLoadingDateField As String
        
        Private bookCarrFinishLoadingTimeField As String
        
        Private bookCarrDockDelAssignmentField As String
        
        Private bookCarrApptDateField As String
        
        Private bookCarrApptTimeField As String
        
        Private bookCarrActDateField As String
        
        Private bookCarrActTimeField As String
        
        Private bookCarrStartUnloadingDateField As String
        
        Private bookCarrStartUnloadingTimeField As String
        
        Private bookCarrFinishUnloadingDateField As String
        
        Private bookCarrFinishUnloadingTimeField As String
        
        Private bookCarrActUnloadCompDateField As String
        
        Private bookCarrActUnloadCompTimeField As String
        
        Private bookShipCarrierNameField As String
        
        Private bookShipCarrierProNumberField As String
        
        Private bookShipCarrierNumberField As String
        
        Private compLegalEntityField As String
        
        Private compAlphaCodeField As String
        
        '''<remarks/>
        Public Property BookCarrOrderNumber() As String
            Get
                Return Me.bookCarrOrderNumberField
            End Get
            Set
                Me.bookCarrOrderNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrDockPUAssigment() As String
            Get
                Return Me.bookCarrDockPUAssigmentField
            End Get
            Set
                Me.bookCarrDockPUAssigmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrScheduleDate() As String
            Get
                Return Me.bookCarrScheduleDateField
            End Get
            Set
                Me.bookCarrScheduleDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrScheduleTime() As String
            Get
                Return Me.bookCarrScheduleTimeField
            End Get
            Set
                Me.bookCarrScheduleTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActualDate() As String
            Get
                Return Me.bookCarrActualDateField
            End Get
            Set
                Me.bookCarrActualDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActualTime() As String
            Get
                Return Me.bookCarrActualTimeField
            End Get
            Set
                Me.bookCarrActualTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActLoadCompleteDate() As String
            Get
                Return Me.bookCarrActLoadCompleteDateField
            End Get
            Set
                Me.bookCarrActLoadCompleteDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActLoadCompleteTime() As String
            Get
                Return Me.bookCarrActLoadCompleteTimeField
            End Get
            Set
                Me.bookCarrActLoadCompleteTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompNumber() As String
            Get
                Return Me.compNumberField
            End Get
            Set
                Me.compNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookPRONumber() As String
            Get
                Return Me.bookPRONumberField
            End Get
            Set
                Me.bookPRONumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookOrderSequence() As Integer
            Get
                Return Me.bookOrderSequenceField
            End Get
            Set
                Me.bookOrderSequenceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartLoadingDate() As String
            Get
                Return Me.bookCarrStartLoadingDateField
            End Get
            Set
                Me.bookCarrStartLoadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartLoadingTime() As String
            Get
                Return Me.bookCarrStartLoadingTimeField
            End Get
            Set
                Me.bookCarrStartLoadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishLoadingDate() As String
            Get
                Return Me.bookCarrFinishLoadingDateField
            End Get
            Set
                Me.bookCarrFinishLoadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishLoadingTime() As String
            Get
                Return Me.bookCarrFinishLoadingTimeField
            End Get
            Set
                Me.bookCarrFinishLoadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrDockDelAssignment() As String
            Get
                Return Me.bookCarrDockDelAssignmentField
            End Get
            Set
                Me.bookCarrDockDelAssignmentField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrApptDate() As String
            Get
                Return Me.bookCarrApptDateField
            End Get
            Set
                Me.bookCarrApptDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrApptTime() As String
            Get
                Return Me.bookCarrApptTimeField
            End Get
            Set
                Me.bookCarrApptTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActDate() As String
            Get
                Return Me.bookCarrActDateField
            End Get
            Set
                Me.bookCarrActDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActTime() As String
            Get
                Return Me.bookCarrActTimeField
            End Get
            Set
                Me.bookCarrActTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartUnloadingDate() As String
            Get
                Return Me.bookCarrStartUnloadingDateField
            End Get
            Set
                Me.bookCarrStartUnloadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrStartUnloadingTime() As String
            Get
                Return Me.bookCarrStartUnloadingTimeField
            End Get
            Set
                Me.bookCarrStartUnloadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishUnloadingDate() As String
            Get
                Return Me.bookCarrFinishUnloadingDateField
            End Get
            Set
                Me.bookCarrFinishUnloadingDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrFinishUnloadingTime() As String
            Get
                Return Me.bookCarrFinishUnloadingTimeField
            End Get
            Set
                Me.bookCarrFinishUnloadingTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActUnloadCompDate() As String
            Get
                Return Me.bookCarrActUnloadCompDateField
            End Get
            Set
                Me.bookCarrActUnloadCompDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookCarrActUnloadCompTime() As String
            Get
                Return Me.bookCarrActUnloadCompTimeField
            End Get
            Set
                Me.bookCarrActUnloadCompTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookShipCarrierName() As String
            Get
                Return Me.bookShipCarrierNameField
            End Get
            Set
                Me.bookShipCarrierNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookShipCarrierProNumber() As String
            Get
                Return Me.bookShipCarrierProNumberField
            End Get
            Set
                Me.bookShipCarrierProNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BookShipCarrierNumber() As String
            Get
                Return Me.bookShipCarrierNumberField
            End Get
            Set
                Me.bookShipCarrierNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompLegalEntity() As String
            Get
                Return Me.compLegalEntityField
            End Get
            Set
                Me.compLegalEntityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CompAlphaCode() As String
            Get
                Return Me.compAlphaCodeField
            End Get
            Set
                Me.compAlphaCodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LastErrorCompletedEventHandler(ByVal sender As Object, ByVal e As LastErrorCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LastErrorCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessDataCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessDataCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessDataCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessDataExCompletedEventHandler(ByVal sender As Object, ByVal e As ProcessDataExCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessDataExCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ReturnMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub ProcessData70CompletedEventHandler(ByVal sender As Object, ByVal e As ProcessData70CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ProcessData70CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Integer
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property ReturnMessage() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),String)
            End Get
        End Property
    End Class
End Namespace
