<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="CompanyFinancial.aspx.cs" Inherits="DynamicsTMS365.CompanyFinancial" %>

<!DOCTYPE html>

<html>
<head>
    <title>DTMS Company Financial</title>
    <%=cssReference%>
    <style>
        html,
        body { height: 100%; margin: 0; padding: 0; }
        html { font-size: 12px; font-family: Arial, Helvetica, sans-serif; overflow: hidden; }
    </style>
</head>
<body>
    <%=jssplitter2Scripts%>
    <%=sWaitMessage%>
    <div id="example" style="height: 100%; width: 100%; margin-top: 2px;">
        <div id="vertical" style="height: 98%; width: 98%;">
            <div id="menu-pane" style="height: 100%; width: 100%; background-color: white;">
                <div id="tab" class="menuBarTab"></div>
            </div>
            <div id="top-pane">
                <div id="horizontal" style="height: 100%; width: 100%;">
                    <div id="left-pane">
                        <div class="pane-content">
                            <% Response.Write(MenuControl); %>
                            <div id="menuTree"></div>
                        </div>
                    </div>
                    <div id="center-pane">
                        <% Response.Write(PageErrorsOrWarnings); %>

                        <!-- begin Page Content -->
                        <% Response.Write(FastTabsHTML); %>
                        <!-- End Page Content -->
                    </div>
                </div>
            </div>
            <div id="bottom-pane" class="k-block" style="height: 100%; width: 100%;">
                <div class="pane-content">
                    <% Response.Write(PageFooterHTML); %>
                </div>
            </div>
        </div>

        <% Response.Write(PageTemplates); %>

        <%-- HelpWindow needs to go after AuthNotification because it uses the notification object created there --%>
        <% Response.Write(AuthLoginNotificationHTML); %>
        <% Response.WriteFile("~/Views/HelpWindow.html"); %>

        <script>
            <% Response.Write(ADALPropertiesjs); %>
            var PageControl = '<%=PageControl%>';
            var tObj = this;
            var tPage = this; 
            var tObjPG = this; 

        <% Response.Write(NGLOAuth2); %>

        

            var blnSaveFromAction = false; //default value //Created By LVV on 7/14/20 for v-8.3.0.001 Task #20200609155542 - Credit Hold

            <% Response.Write(PageCustomJS); %>

            //************* Action Menu Functions ********************
            function execActionClick(btn, proc){
                if(btn.id == "btnOpenCompany" ){ location.href = "LECompMaint";}
                else if(btn.id == "btnUpdateCreditNow" ){
                    //Created By LVV on 7/14/20 for v-8.3.0.001 Task #20200609155542 - Credit Hold
                    blnSaveFromAction = true; //save was generated by action button click
                    wdgtepCompFinancialsEdit.save();
                }             
                else if(btn.id == "btnRefresh" ){ refresh(); }  
                else if(btn.id == "btnResetCurrentUserConfig"){ resetCurrentUserConfig(PageControl); }  
                else if(btn.id=="btnOpenCompEDI"){ location.href = "CompEDI";}                 
            }

            function refresh(){ 
                if(wdgtepCompFinancialsEdit){ wdgtepCompFinancialsEdit.read(0); } 
            }
             
            //************* Call Back Functions **********************        
            function savePostPageSettingSuccessCallback(results){
                //for now do nothing when we save the pk
            }
            function savePostPageSettingAjaxErrorCallback(xhr, textStatus, error){
                //for now do nothing when we save the pk           
            }      


            //Created By LVV on 7/14/20 for v-8.3.0.001 Task #20200609155542 - Credit Hold
            function epCompFinancialsCB(oResults){
                if ( oResults.source == "saveSuccessCallback")
                {
                    //If the save originated from the Action Button click, we need to run the UpdateCreditNow! code after the save
                    //If the save originated from the save button on the page, we need to show a warning message that changes will not go into effect until the action button is clicked
                    if(blnSaveFromAction){
                        $.ajax({
                            type: "GET",
                            url: "api/CompFinancial/UpdateCreditNowSingle",
                            contentType: "application/json; charset=utf-8",
                            dataType: 'json',
                            headers: { "Authorization": localStorage.NGLvar1454, "USC": localStorage.NGLvar1452 },
                            success: function (data) {
                                try {
                                    var blnSuccess = false, blnErrorShown = false;
                                    var strValidationMsg = "There was a problem while executing the Update Credit Routine";
                                    if (typeof (data) !== 'undefined' && ngl.isObject(data)) {
                                        if (ngl.stringHasValue(data.Errors)) { blnErrorShown = true; ngl.showErrMsg("Update Credit Routine Failure", data.Errors, null); }
                                        if (ngl.stringHasValue(data.Messages)) { blnSuccess = true; ngl.showSuccessMsg(data.Messages, null); }
                                    }
                                    if (blnSuccess === false && blnErrorShown === false) { ngl.showErrMsg("Update Credit Routine Failure", strValidationMsg, null); }
                                } catch (err) { ngl.showErrMsg(err.name, err.description, null); }
                            },
                            error: function (xhr, textStatus, error) { kendo.ui.progress(wndCreditLimits.element, false); var sMsg = formatAjaxJSONResponsMsgs(xhr, textStatus, error, "Save Data Failure"); ngl.showErrMsg("Update Credit Routine Failure", sMsg, null); }
                        });
                    } else { ngl.showSuccessMsg("Changes to Credit will not go into effect until the Update Credit Now! button is clicked", null); }
                    blnSaveFromAction = false; //reset the variable to false by default
                }
            }


            //************* Page Functions ***************************


            $(function () {
                //wire focus of all numerictextbox widgets on the page
                $("input[type=number]").bind("focus", function () {
                    var input = $(this);
                    clearTimeout(input.data("selectTimeId")); //stop started time out if any
                    var selectTimeId = setTimeout(function(){ input.select(); });
                    input.data("selectTimeId", selectTimeId);
                }).blur(function(e) {
                    clearTimeout($(this).data("selectTimeId")); //stop started timeout
                });
            });

            $(document).ready(function () {
                var PageMenuTab = <%=PageMenuTab%>;                    
                                                       
                if (control != 0){


                } 
                var PageReadyJS = <%=PageReadyJS%>;
                menuTreeHighlightPage(); //must be called after PageReadyJS
                var divWait = $("#h1Wait");                          
                if (typeof (divWait) !== 'undefined' ) { divWait.hide(); }        
            });
        </script>
        <style>
            .k-grid tbody tr td { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
            .k-tooltip { max-height: 500px; max-width: 450px; overflow-y: auto; }
            .k-grid tbody .k-grid-Edit { min-width: 0; }
            .k-grid tbody .k-grid-Edit .k-icon { margin: 0; }
            /*This fixes thead icon alignment in thead grid buttons. Now the right side doesn't get cut off and it looks more centered. Should probably add this code to common.css */    
            .k-button-icontext .k-icon, .k-button-icontext .k-image, .k-button-icontext .k-sprite { margin-right:0; }
        </style>
    </div>
</body>
</html>